### ISSUE TITLE
r10k gem version needs updating

### ISSUE THREAD

**Issue by annaken** [acidprime/r10k#153]
The params file refers to r10k gem version 1.5.0, but it's now been replaced with 1.5.1 and 1.5.0 is not available any more:
https://rubygems.org/gems/r10k/versions

**Comment by gjngeldenhuis** [comment]
Confirmed the same error. A simple update in params.pp does the trick for now. Would it be worthwhile to set the version to be latest rather than a specific version. Alternatively if rubygems held more than one version at a time that would also be a viable longer term solution.

**Comment by annaken** [comment]
I think 1.5.0 has been explicitly removed, certainly other older versions are still available.
I agree that updating in params fixes the issue - I didn't think it was worth submitting a patch for a single digit change.

**Comment by iansu** [comment]
I'm having the same problem. As a workaround you can specify the version when using the r10k module:
```
class { 'r10k':
  version => '1.5.1'
}
```

**Comment by acidprime** [comment]
Thanks all, yeah adrian pulled the release as it had a major bug with tracking branches that we did not find until friday after its release date. It was fixed but because it was a tricky error he pulled the release. I don't want to go down the latest road as thats not really something I feel like should be done with a module that is only tested a version at a time. The `version` param is the right way to do things for now and params is basically what has been tested
